method:
  id: "rtr_gs"
  output_path: "/mnt/output/rtr_gs"
  working_directory: "/workspace/RTR-GS"
  python: "/mnt/conda/rtr-gs/bin/python"
  multi_stage: true
  evaluate_normal_mae: true
  
stages:
  training:
    stage1:
      script: train.py
      output_path_template: "{model_path}/stage1"
      args: 
        base: " --eval --ref_map --compute_with_prt --diffuse_iteration 3000 --skip_eval -t render_ref"
        real: " --lambda_normal_render_depth 0.01 --densify_grad_threshold 0.0005"
        synthetic: " --lambda_mask_entropy 0.1"

    baking:
      script: baking.py
      no_extra_args: true
      args: " --checkpoint {model_path}/stage1/checkpoint/chkpnt30000.pth --bound 2.0 --occlu_res 128"

    stage2:
      script: train.py
      output_path_template: "{model_path}/stage2"
      args:
        base: " --eval --ref_map --compute_with_prt -c {model_path}/stage1/checkpoint/chkpnt30000.pth --occlusion_path  {model_path}/stage1/checkpoint/occlusion_volumes.pth --iterations 40000 -t render_ref_pbr"
        real: " --save_training_vis --lambda_ref_strength_smooth 0.01 --lambda_reflect_strength_equal_metallic 0.0"
        synthetic: " --lambda_mask_entropy 0.1 --lambda_reflect_strength_equal_metallic 0.1 --skip_eval --metallic"

  rendering:
    script: render_and_eval.py
    output_path_template: "{model_path}/stage2"
    args:
      base: " --checkpoint {model_path}/stage2/checkpoint/chkpnt40000.pth --occlusion_path {model_path}/stage1/checkpoint/occlusion_volumes.pth --ref_map --compute_with_prt --metallic -t render_ref_pbr"

  mae_evaluation:
    script: eval_mae.py
    output_path_template: "{model_path}/stage2"
    args: ""

  fps_evaluation:
    script: eval_fps.py
    output_path_template: "{model_path}/stage2"
    args:
      base: " -t render_ref --ref_map --compute_with_prt"
      real: " --checkpoint {model_path}/stage2/checkpoint/chkpnt40000.pth --occlusion_path {model_path}/stage1/checkpoint/occlusion_volumes.pth"
      synthetic: " --checkpoint {model_path}/stage2/checkpoint/chkpnt40000.pth --occlusion_path {model_path}/stage1/checkpoint/occlusion_volumes.pth --metallic"

  collect:
    output_path_template: "{model_path}/stage2"
    args: ""