method:
  id: ref-gs
  output_path: "/mnt/output/ref_gs"
  working_directory: "/workspace/Ref-GS"
  python: "/mnt/conda/ref_gs/bin/python"
  evaluate_normal_mae: true

stages:
  training:
    script: train-real.py
    args: 
      base: " --disable_viewer --quiet --eval --test_iterations -1 --save_iterations -1"
      real: " --run_dim 256 --albedo_bias 2 --albedo_lr 0.0005"
    scene_overrides:
      envgs/audi: " --env_scope_center -0.032 0.808 0.751 --env_scope_radius 4"
      envgs/dog: " --env_scope_center -0.2270 1.9700 1.7740 --env_scope_radius 5"
      shiny_blender/helmet: " --run_dim 256 --albedo_bias 0"
      shiny_blender/car: " --run_dim 256 --albedo_bias 0"
      shiny_blender/ball: " --run_dim 256 --albedo_bias 0"
      shiny_blender/teapot: " --run_dim 256 --albedo_bias 0"
      shiny_blender/coffee: " --run_dim 256 --albedo_bias 0 --albedo_lr 0.002"
      shiny_blender/toaster: " --run_dim 256 --albedo_bias 0"

  rendering:
    script: render-real.py
    args: " --quiet --eval --skip_train"

  fps_evaluation:
    script: eval_fps-real.py
    args: ""