method:
  id: 3dgs-dr
  output_path: "/mnt/output/3dgs-dr"
  working_directory: "/workspace/3DGS-DR"
  python: "/mnt/conda/gaussian_splatting_3.11/bin/python"
  evaluate_normal_mae: true

stages:
  training:
    script: train.py
    args: 
      base: " --quiet --eval --iterations 61000 --test_iterations -1 --save_iterations -1"
      real: " --longer_prop_iter 36_000"
    scene_overrides:
      envgs/audi: " --use_env_scope --env_scope_center -0.032 0.808 0.751 --env_scope_radius 4"
      envgs/dog: " --use_env_scope --env_scope_center -0.2270 1.9700 1.7740 --env_scope_radius 5"
      shiny_blender/toaster: " --longer_prop_iter 24_000"

  rendering:
    script: render.py
    args: " --quiet --eval --skip_train"

  metrics_evaluation:
    script: metrics.py
    args: ""

  fps_evaluation:
    script: eval_fps.py
    args: ""

  mae_evaluation:
    script: eval_mae.py
    args: ""
    
  render_videos:
    script: render-videos.py
    args: ""
    scene_overrides:
      envgs/audi: " --path arc"